PermitRootLogin prohibit-password
KbdInteractiveAuthentication no
PasswordAuthentication yes
StreamLocalBindUnlink yes
AllowAgentForwarding no
AllowTcpForwarding no
PermitEmptyPasswords 
IgnoreRhosts yes
X11Forwarding no
PermitTunnel no
DebianBanner no
MaxAuthTries 3
MaxSessions 1
Banner none
Protocol 2